import Head from "next/head";
import Image from "next/image";

import Dnt from "../public/dnt.png";

export default function Home() {
    return (
        <>
            <Head>
                <title>Elin har bursdag!🥳🎈👵🏼</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className=''>
                <h1 className=' text-center pb-4 text-[32px]  text-purple-700'>
                    Gratulerer med dagen
                    <br /> gamle nabo!🥳🎈👵🏼
                </h1>
                <div className=' flex justify-center'>
                    <Image src={Dnt} />
                </div>
            </main>
        </>
    );
}
